FROM golang:1.23

WORKDIR /app

COPY . .

RUN go build -o main ./cmd/go-todo-sqlite

EXPOSE 8080

ENV PORT=8080
ENV GIN_MODE=release
ENV DATABASE_URL=./todo.db

# Command to run the application
CMD ["./main"]